basePath: /v1
definitions:
  pojo.User:
    properties:
      UserBirthday:
        type: string
      UserEmail:
        type: string
      UserId:
        type: integer
      UserName:
        type: string
      UserPassword:
        type: string
    type: object
host: 127.0.0.1:8000
info:
  contact: {}
  description: This is sample of practicing API to get data in MySQL
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API
  version: "1.0"
paths:
  /users/:
    get:
      description: get ID, Name,Password,Email and Birthday of all users in MySQL
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pojo.User'
            type: array
      summary: Get All User
      tags:
      - MySQL
  /users/search:
    delete:
      description: delete ID, Name,Password,Email and Birthday by  user's id in MySQL
      parameters:
      - description: id
        in: query
        name: Id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pojo.User'
            type: array
      summary: Delete User by Id
      tags:
      - MySQL
    get:
      description: get ID, Name,Password,Email and Birthday by  user's id in MySQL
      parameters:
      - description: id
        in: query
        name: Id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pojo.User'
            type: array
      summary: Get User by Id
      tags:
      - MySQL
    post:
      description: post ID, Name,Password,Email and Birthday by  user's id in MySQL
      parameters:
      - description: id
        in: query
        name: Id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pojo.User'
            type: array
      summary: Post User by Id
      tags:
      - MySQL
swagger: "2.0"
